### ISSUE TITLE
Xhr adapter doesn't JSON.parse(body)?

### ISSUE THREAD

**Issue by noobiek** [apicase/apicase-adapter-xhr#2]
Hi,

Why is implementation of adapter-fetch is so different from adapter-xhr?
Fetch parses response body and xhr doesn't. This makes switch from xhr to fetch and vice versa impossible.
Or do I miss something?

Thanks!

**Comment by Kelin2025** [comment]
Seems like a bug. I'll check it asap

**Comment by Kelin2025** [comment]
Fixed in [v0.7.0](https://github.com/apicase/adapter-xhr/releases/tag/v0.7.0). Please run   
```
yarn add @apicase/adapter-xhr@latest
```

**Comment by noobiek** [comment]
thanks!
