### ISSUE TITLE
Please move "ghooks" to devDependencies

### ISSUE THREAD

**Issue by tmcdos** [apicase/apicase-adapter-xhr#3]
Please move `ghooks` from `dependencies` to `devDependencies` as described in the README
![shot-1](https://user-images.githubusercontent.com/19253115/57707039-954fe780-766f-11e9-8592-9a9975da5fba.png)
Otherwise it slips into the production environment which is very undesired.
Thank you.

**Comment by Kelin2025** [comment]
My bad, will fix asap

**Comment by Kelin2025** [comment]
Fixed, forgot to close the issue
